kind: pipeline
type: docker
name: deploy

steps:
  - name: build-and-deploy
    image: docker
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker build -t tidal-dl .
      - docker stop tidal-dl || true
      - docker rm tidal-dl || true
      - docker-compose up -d

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
